name: CI-CD

on:
  push:
    tags:
    branches:
  pull_request:
    branches: ["**"]
    types: [opened, synchronize, reopened, edited]

defaults:
  run:
    working-directory: src

jobs:
  test:
    name: 🛠 Build, 🧪 Test
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: 🟣 Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 🌴 dotnet restore
        run: dotnet restore

      - name: 🛠 dotnet build
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 dotnet test
        run: dotnet test --configuration Release --no-restore

  version:
    name: 1️⃣2️⃣3️⃣ VERSION from tag
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.get-version.outputs.success }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: 1️⃣2️⃣3️⃣ Get VERSION
        id: get-version
        uses: ./.github/actions/version

  publish:
    name: 📦 Publish to NuGet
    runs-on: ubuntu-latest
    needs:
      - test
      - version
    if: needs.test.result == 'success' && needs.version.outputs.success == 'true'

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: 🟣 Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 📦 Pack 🚀 Push
        uses: ./.github/actions/nuget
        with:
          working-directory: src
          api-key: ${{ secrets.NUGET_API_KEY }}
          version: ${{ needs.version.outputs.version }}
