name: 🔄 Sync Material Design
# https://stackoverflow.com/a/58468828
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"
defaults:
  run:
    working-directory: src/Projektanker.Icons.Avalonia.MaterialDesign

jobs:
  sync:
    name: 🔄 Sync Material Design
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 1️⃣2️⃣3️⃣ Increase minor VERSION
        id: get-version
        uses: ./.github/actions/minor-version

      - name: 📥 Download repository archive
        run: wget -O archive.zip https://github.com/Templarian/MaterialDesign-SVG/archive/master.zip

      - name: 📦 unzip archive
        run: unzip archive.zip -d temp

      - name: 🧹 Clear Assets directory
        run: rm ./Assets/*

      - name: 🚚 Move *.svg to Assets directory
        run: find temp -iname '*.svg' -type f -exec mv -nv -t 'Assets' -- {} +

      - name: 🧹 Remove temporary files
        run: |
          rm -r ./temp
          rm archive.zip

      - name: ℹ git status
        run: git status

      - name: 🔎 Check for modified files
        id: git-check
        run: echo modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true") >> $GITHUB_OUTPUT

      - name: 🟣 Setup .NET 7.0
        if: steps.git-check.outputs.modified == 'true'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 🧪 dotnet test
        if: steps.git-check.outputs.modified == 'true'
        run: dotnet test --configuration Release

      - name: 💬 Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name '${{ secrets.GIT_USER }}'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git add .
          git commit -m "feat(Material Design): 🔄 icons changed."
          git tag ${{ steps.get-version.outputs.version }}
          git push && git push --tags

      - name: 📦 Pack 🚀 Push
        if: steps.git-check.outputs.modified == 'true'
        uses: ./.github/actions/nuget
        with:
          working-directory: src
          api-key: ${{ secrets.NUGET_API_KEY }}
          version: ${{ steps.get-version.outputs.version }}
